[features]
seeds = false
skip-lint = false
[programs.localnet]
vault_playground = "8HgHuULD1mrHTmtLVQuuvimcEVkswoeFZn2iNz7A22w5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
